name = "nock-ezpz-www"
compatibility_date = "2025-08-10"
workers_dev = false

routes = [{ pattern = "nock.ezpz.sh/*", zone_name = "ezpz.sh" }]

[assets]
directory = "./"
not_found_handling = "single-page-application"
