name = "nock-ezpz-sh"
compatibility_date = "2026-01-27"
workers_dev = false

routes = [{ pattern = "nock.ezpz.sh/*", zone_name = "ezpz.sh" }]

[assets]
directory = "./"
not_found_handling = "single-page-application"
