name = "nock-ezpz-ui"
compatibility_date = "2025-08-10"
workers_dev = false

[assets]
directory = "./"
not_found_handling = "single-page-application"

routes = [ { pattern = "nock.ezpz.sh/*", zone_name = "ezpz.sh" } ]
