name = "nock-ezpz-api"
main = "src/index.js"
compatibility_date = "2025-08-10"
workers_dev = false

routes = [ { pattern = "api.nock.ezpz.sh/*", zone_name = "ezpz.sh" } ]

[[r2_buckets]]
binding = "FILES"
bucket_name = "files"

[[kv_namespaces]]
binding = "AUTH"
id = "bfb2b2405536457f9d54c2a2993cb0aa"

[vars]
PUBLIC_PREFIX = "pub/"
RESTRICTED_PREFIX = "priv/"
POLICY_KEY = "config/policy.json"
CACHE_SECONDS = "60" # Useful for the website
